name = "MarkovianClosure"
uuid = "f4258524-7353-4a9f-9916-8287adc6b2b5"
authors = ["Davide Ferracin <davide.ferracin@protonmail.com> and contributors"]
version = "0.1.9"

[deps]
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
LindbladVectorizedTensors = "6455c26f-8985-4381-925b-8a93509e9dbd"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
